// Customizable Area Start
import React from "react";
import {
  Container,
  Typography,
  withStyles,
  Button,
  IconButton,
  Divider,
  Box,
  Grid,
  Dialog,
  DialogContent,
  DialogActions,
  Card,
  FormControl,
  TextareaAutosize,
} from "@material-ui/core";
import AuditReportDetailsController, { Props } from "./AuditReportDetailsController.web";
import DashboardHeader from "../../dashboard/src/DashboardHeader.web";
import ChairmanSidebarWeb from "../../dashboard/src/ChairmanSidebar.web";
import { withTranslation } from "react-i18next";
import "web/src/i18n";
import { ReportsStyleWeb } from "./ReportsStyle.web";
import { CheckIcon } from "../../user-profile-basic/src/assets";
import MuiDialogTitle from "@material-ui/core/DialogTitle";
import CloseIcon from "@material-ui/icons/Close";
import { DownloadIcon, PdfIcon } from "./assets";

class AuditReportDetails extends AuditReportDetailsController {
  constructor(props: Props) {
    super(props);
  }

  render() {
    const { t, classes }: any = this.props;

    return (
      <>
        <Box style={{ background: "#F4F7FF" }} className={classes.reportDetails}>
          {/* Dashboard Header -- */}
          <DashboardHeader {...this.props} />
          <Box style={{ display: "flex" }}>
            <Grid item xs={3} md={3} sm={3} className="SideBar">
              {/* Chairman Sidebar -- */}
              <ChairmanSidebarWeb {...this.props} />
            </Grid>

            <Grid item xs={9} md={9} sm={9} style={{ paddingTop: 35 }}>
              <Container>
                <Box className="navigation">
                  <Typography variant="body1">
                    {t("Documents & Reports")} / {t("Reports")} / {t("Audit Reports")} /{" "}
                    <Box component="span" style={{ color: "blue" }}>
                      {t("Audit Report Details")}
                    </Box>
                  </Typography>
                  <Typography variant="h5" className="sub-heading">
                    {t("Audit Report Details")}
                  </Typography>
                </Box>

                <Box className="budget-box audit-box">
                  <Card>
                    <Box className="heading">
                      <h4>Report Details</h4>
                      <span className="pending">{t("Pending Approval")}l</span>
                    </Box>
                    <Divider />
                    <Box className="budget-content-box">
                      <Box className="content-line">
                        <p>Year</p>
                        <span>2022</span>
                      </Box>
                      <hr />
                      <Box className="content-line">
                        <p>Report Generated on</p>
                        <span>12 Dec 2022</span>
                      </Box>
                      <hr />
                      <Box className="content-line">
                        <p>Report Generated By</p>
                        <span>John Doe</span>
                      </Box>
                      <Box className="report-pdf-box">
                        <Box className="left-side">
                          <img src={PdfIcon} alt="" />
                          <span>Report</span>
                        </Box>
                        <img src={DownloadIcon} alt="" />
                      </Box>
                    </Box>
                  </Card>
                </Box>

                <Box className="rejection-box">
                  <Card>
                    <h4>{t("Rejection Reason")}</h4>
                    <p>
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, recusandae delectus. Non rem sequi
                      dignissimos porro incidunt quas quis nam libero, culpa, dolorem architecto quod iure minus
                      mollitia labore. Id?
                    </p>
                  </Card>
                </Box>

                <Box className="button-box">
                  <Button className="cancel" onClick={() => this.handleRejectReportModal()}>
                    {t("Reject")}
                  </Button>
                  <Button className="edit" onClick={() => this.handleApproveReportModal()}>
                    {t("Approve")}
                  </Button>
                </Box>
              </Container>
            </Grid>
          </Box>
        </Box>

        <Dialog fullWidth className="add-meeting" open={this.state.isRejectReportModalOpen}>
          <MuiDialogTitle disableTypography className="dialog-heading">
            <Typography variant="h6">Reject Audit Report</Typography>
            <IconButton onClick={() => this.handleRejectReportModal()}>
              <CloseIcon />
            </IconButton>
          </MuiDialogTitle>
          <DialogContent dividers>
            <FormControl fullWidth>
              <TextareaAutosize className="reject-note" placeholder={t("Add Notes")} />
            </FormControl>
          </DialogContent>
          <DialogActions className="dialog-button-group">
            <Button className="cancel-button" onClick={() => this.handleRejectReportModal()}>
              {t("Cancel")}
            </Button>
            <Button className="add-button">{t("Submit")}</Button>
          </DialogActions>
        </Dialog>

        <Dialog
          fullWidth
          onClose={() => this.handleApproveReportModal()}
          open={this.state.isApproveReportModalOpen}
          className="cancel-meeting-dialog"
        >
          <DialogContent style={{ margin: "15px 0" }}>
            <Box textAlign="center">
              <img className="comment-image" src={CheckIcon} alt="check" />
              <Typography variant="h6">Approve Audit Report</Typography>
              <Typography variant="body1" style={{ marginBottom: "0px" }}>
                Are you sure you want to approve audit report?
              </Typography>
              <DialogActions className="dialog-button-group">
                <Button
                  className="cancel-button"
                  style={{ width: "200px" }}
                  onClick={() => this.handleApproveReportModal()}
                >
                  {t("Close")}
                </Button>
                <Button style={{ width: "200px" }} className="add-button">
                  {t("Approve")}
                </Button>
              </DialogActions>
            </Box>
          </DialogContent>
        </Dialog>
      </>
    );
  }
}

export default withTranslation()(withStyles(ReportsStyleWeb)(AuditReportDetails));

// Customizable Area End
